name: Publish to GitHub Packages

on:
    push:
        branches: [ "master" ]
    release:
        types: [ created ]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write

        steps:
            -   uses: actions/checkout@v4

            -   name: Validate Tag Version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    if [[ ! ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo "Error: Tag must follow SemVer format (vX.Y.Z)"
                      exit 1
                    fi
            -   name: Verify POM Version matches Tag
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    TAG_VERSION=${GITHUB_REF#refs/tags/v}
                    POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                    if [[ "$POM_VERSION" != "$TAG_VERSION" ]]; then
                      echo "Error: pom.xml version ($POM_VERSION) does not match tag ($TAG_VERSION)"
                      exit 1
                    fi
            -   name: Reject SNAPSHOT tags
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    if [[ ${{ github.ref }} == *"-SNAPSHOT"* ]]; then
                      echo "Error: Tags must not contain '-SNAPSHOT'"
                      exit 1
                    fi
            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    server-id: github
                    settings-path: ${{ github.workspace }}

            -   name: Cache Maven packages
                uses: actions/cache@v3
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2-

            -   name: Check CPU cores
                run: |
                    echo "Number of CPU cores: $(nproc)"
                    echo "CPU info:"
                    lscpu
            -   name: Build and Test
                run: mvn -B clean verify

            -   name: Publish to GitHub Packages (on tag)
                if: startsWith(github.ref, 'refs/tags/')
                run: mvn -B deploy -DskipTests
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}